language: python

python:
  - "3.5.3"

# Dependencias do projeto
install:
  - pip install -r radar_parlamentar/requirements.txt

# Roda Testes
script:
   - cd radar_parlamentar/ ; source tests.sh
   - coverage run --source=modelagem,analises,exportadores,importadores,radar_parlamentar manage.py test modelagem analises exportadores importadores radar_parlamentar

after_success:
  - coveralls
